### ISSUE TITLE
AWTCY (AreWeToxClientYet)?

### ISSUE THREAD

**Issue by silvioprog** [tox-rs/tox#427]
Hi.

Thanks for this project! 👍 

So, is there any client like qTox/uTox using `tox-rs`? If so, could you share its link?!

Thank you!

**Comment by kpp** [comment]
No. Our best result was an echo bot (sends back every message): https://github.com/tox-rs/tox/blob/master/examples/echo.rs

**Comment by suhr** [comment]
It may be worth to keep this as a goal though.

**Comment by FrontMage** [comment]
Hi, I've been trying to get echo bot to work, but I can't add the echo bot to a friend with the qtox client.
It just always shows the friend status is not online, even if I did turn on the lan discovery.
I'm using manjaro linux, is there any settings I'm missing? Please help!

**Comment by kpp** [comment]
Did you try to send something to the bot? We could have missed sending "Status::Online" to friends.

**Comment by kurnevsky** [comment]
This error is fine if you restarted the node before - other nodes remember your old key and send packets your new instance can't decrypt.

But anyway there can be bugs in the implementation - we didn't test this part thoroughly.

**Comment by FrontMage** [comment]
> Did you try to send something to the bot? We could have missed sending "Status::Online" to friends.

Yeah, I did, the qtox client is just kept spinning, indicates that message is not received.

**Comment by kurnevsky** [comment]
@FrontMage should be fixed with https://github.com/tox-rs/tox/pull/431

**Comment by FrontMage** [comment]
@kurnevsky I pulled the latest version of the master branch, still no luck with qtox. My friend got it working though, but he is on macOS, maybe there is something wrong with my network settings, I'm trying to debug.
Thanks for the fix!
