### ISSUE TITLE
Lan Discovery segfault

### ISSUE THREAD

**Issue by kpp** [tox-rs/tox#76]
When running `$ cargo run --example dht_node`

```
Starting program: /home/humbug/zetox/target/debug/examples/dht_node 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff69ff700 (LWP 25611)]
[New Thread 0x7ffff63ff700 (LWP 25612)]
[New Thread 0x7ffff5dff700 (LWP 25613)]
[New Thread 0x7ffff57ff700 (LWP 25614)]
nat_wakeup
recv = DhtRequest(DhtRequest { rpk: PublicKey([15, 107, 126, 130, 81, 55, 154, 157, 192, 117, 0, 225, 119, 43, 48, 117, 84, 109, 112, 57, 243, 216, 4, 171, 185, 111, 33, 146, 221, 31, 77, 118]), spk: PublicKey([186, 227, 149, 99, 76, 17, 146, 164, 92, 0, 135, 84, 26, 241, 252, 149, 204, 231, 16, 144, 3, 178, 95, 170, 117, 146, 85, 171, 55, 236, 155, 123]), nonce: Nonce([125, 237, 186, 21, 65, 189, 85, 24, 226, 60, 155, 217, 29, 118, 253, 5, 234, 67, 113, 199, 74, 13, 217, 251]), payload: [231, 125, 48, 121, 172, 244, 85, 240, 54, 170, 147, 106, 183, 87, 71, 69, 128, 26, 136, 200, 225, 140, 143, 26, 216, 151] })
nat_wakeup
recv = DhtRequest(DhtRequest { rpk: PublicKey([15, 107, 126, 130, 81, 55, 154, 157, 192, 117, 0, 225, 119, 43, 48, 117, 84, 109, 112, 57, 243, 216, 4, 171, 185, 111, 33, 146, 221, 31, 77, 118]), spk: PublicKey([186, 227, 149, 99, 76, 17, 146, 164, 92, 0, 135, 84, 26, 241, 252, 149, 204, 231, 16, 144, 3, 178, 95, 170, 117, 146, 85, 171, 55, 236, 155, 123]), nonce: Nonce([139, 241, 179, 179, 95, 133, 79, 59, 229, 252, 46, 221, 122, 137, 147, 157, 216, 65, 94, 219, 204, 64, 143, 160]), payload: [215, 123, 23, 74, 183, 63, 237, 66, 78, 129, 78, 192, 192, 112, 250, 21, 104, 197, 20, 103, 168, 32, 50, 159, 139, 255] })
nat_wakeup
recv = DhtRequest(DhtRequest { rpk: PublicKey([15, 107, 126, 130, 81, 55, 154, 157, 192, 117, 0, 225, 119, 43, 48, 117, 84, 109, 112, 57, 243, 216, 4, 171, 185, 111, 33, 146, 221, 31, 77, 118]), spk: PublicKey([186, 227, 149, 99, 76, 17, 146, 164, 92, 0, 135, 84, 26, 241, 252, 149, 204, 231, 16, 144, 3, 178, 95, 170, 117, 146, 85, 171, 55, 236, 155, 123]), nonce: Nonce([40, 29, 28, 143, 170, 224, 191, 18, 6, 16, 7, 201, 203, 180, 240, 78, 11, 57, 173, 78, 85, 56, 195, 136]), payload: [87, 64, 179, 28, 187, 46, 104, 118, 191, 40, 161, 20, 177, 51, 213, 26, 148, 60, 216, 224, 132, 16, 13, 45, 119, 5] })
lan_wakeup

Thread 4 "tokio-runtime-w" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff5dff700 (LWP 25613)]
0x00005555557e8e03 in get_if_addrs::getifaddrs_posix::sockaddr_to_ipaddr::haaf65eefab8dbaee (sockaddr=0x0)
    at /home/humbug/.cargo/registry/src/github.com-1ecc6299db9ec823/get_if_addrs-0.5.0/src/lib.rs:163
163	        let sa_family = u32::from(unsafe { *sockaddr }.sa_family);
```

```
   │130         // get broadcast addresses for host's network interfaces                                                   │
   │131         fn get_ipv4_broadcast_addrs() -> Vec<IpAddr> {                                                             │
  >│132             let ifs = get_if_addrs::get_if_addrs().expect("no network interface");                                 │
   │133             ifs.iter().filter_map(|interface|                                                                      │
   │134                 match interface.addr {                                                                             │
   │135                     IfAddr::V4(ref addr) => addr.broadcast,                                                        │
   │136                     _ => None,                                                                                     │
   │137             })                                                                                                     │
   │138             .map(|ipv4|                                                                                            │
   │139                 IpAddr::V4(ipv4)                                                                                   │
   │140             ).collect()                                                                                            │
   │141         }       
```

**Comment by kpp** [comment]
```
   │161         #[allow(unsafe_code)]                                                                                      │
   │162         fn sockaddr_to_ipaddr(sockaddr: *const posix_sockaddr) -> Option<IpAddr> {                                 │
  >│163             let sa_family = u32::from(unsafe { *sockaddr }.sa_family);                                             │
   │164                                                                                                                    │
   │165             if sockaddr.is_null() {                                                                                │
   │166                 return None;                                                                                       │
   │167             }    
```

```
(gdb) p sockaddr
$3 = (struct sockaddr *) 0x0
```

**Comment by kpp** [comment]
Anyway after local hotfix in `get_if_addrs` I get:

```
lan_wakeup
ERROR 2018-03-31T12:01:07Z: dht_node: Processing ended with error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
ERROR 2018-03-31T12:01:07Z: dht_node: Processing ended with error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
```

**Comment by kpp** [comment]
```
$ ifconfig -a
```

```
enp0s31f6 Link encap:Ethernet  HWaddr 18:db:f2:48:2a:dc  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
          Interrupt:16 Память:ef300000-ef320000 

lo        Link encap:Локальная петля (Loopback)  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:302997 errors:0 dropped:0 overruns:0 frame:0
          TX packets:302997 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:64500311 (64.5 MB)  TX bytes:64500311 (64.5 MB)

wlp2s0    Link encap:Ethernet  HWaddr f0:d5:bf:e6:65:18  
          inet addr:192.168.1.192  Bcast:192.168.1.255  Mask:255.255.255.0
          inet6 addr: 2a02:2168:2343:4600:8dbf:a92b:c002:1907/64 Scope:Общий
          inet6 addr: fe80::1ba9:66e2:9686:5db1/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:4698713 errors:0 dropped:0 overruns:0 frame:0
          TX packets:3084508 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:4090597080 (4.0 GB)  TX bytes:476434714 (476.4 MB)
```

**Comment by NamsooCho** [comment]
The reason of "Permission denied" is that the socket was not have right to send packet to broadcast address.
Now, it is fixed. close this.

**Comment by kpp** [comment]
It is not fixed since there is a bug in our repo. It will be fixed only when #78 is merged
